run_id: EDIT_RUN_ID
pipeline_name: nfcore-rnaseq-processing
dataset_id: EDIT_DATASET_ID
project_id: EDIT_PROJECT_ID

execution:
  platform: CREATE_HPC
  slurm_launcher: nextflow_run.sh
  profile: create
  project_scratch_base: /scratch/prj/bcn_whitema_rbp/EDIT_PROJECT_ID
  project_rds_root: /rds/prj/bcn_whitema_rbp
  user_scratch_runstate: /scratch/users/EDIT_USERNAME/nextflow_runstate/EDIT_PROJECT_ID
  user_cache_root: /scratch/users/EDIT_USERNAME/nextflow_cache
  work_dir: /scratch/prj/bcn_whitema_rbp/EDIT_PROJECT_ID/work

pipeline:
  nfcore_pipeline: rnaseq
  nfcore_version: "3.23.0"
  nextflow_version: "25.10.4"
  aligner: star_salmon

inputs:
  samplesheet: /scratch/prj/bcn_whitema_rbp/EDIT_PROJECT_ID/launch/samplesheet.csv
  canonical_samplesheet: /scratch/prj/bcn_whitema_rbp/EDIT_PROJECT_ID/launch/samplesheet.canon.csv
  sample_metadata: /scratch/prj/bcn_whitema_rbp/EDIT_PROJECT_ID/launch/sample_metadata.csv

reference:
  organism: Homo sapiens
  genome_build: GRCh38
  annotation_source: GENCODE
  annotation_release: EDIT_ANNOTATION_RELEASE
  fasta: /absolute/path/to/reference.fa.gz
  gtf: /absolute/path/to/annotation.gtf.gz
  gencode_mode: true

notes:
  - "Replace all EDIT_ fields before use."
