pipeline_name: nfcore-rnaseq-processing
pipeline_version_status: development

nfcore:
  pipeline: rnaseq
  version: "3.23.0"
  profile: create
  aligner: star_salmon

references:
  organism: Homo sapiens
  genome_build: GRCh38
  annotation_source: GENCODE
  annotation_release: "v49"
  gencode_mode: true

execution:
  save_align_intermeds: true
  save_reference: true

create:
  project_scratch_root: /scratch/prj/bcn_whitema_rbp
  project_rds_root: /rds/prj/bcn_whitema_rbp
